summarizer_and_conversational_script_writer_task:
  description: >
    Summarize the content into key points suitable for conversational podcast dialogue.
  expected_output: >
    A conversational script between two podcast hosts (Giggles and Chuckles) in JSON format.
  agent: summarizer_and_conversational_script_writer

audio_producer_task:
  description: >
    Generate audio using the script.
  expected_output: >
    Audio files in MP3 format for each of the two speakers (Chuckles and Giggles).
  agent: audio_producer

podcast_audio_producer_task:
  description: >
    Merge the audio files into a single podcast file.
  expected_output: >
    An audio file in MP3 format.
  agent: podcast_audio_producer